In [ ]:
!pip install numpy

In [ ]:
#import numpy as np
#creating numpy array using np.array

import numpy as np
lst = [1,2,3,4,5]
arr1 = np.array(lst)  # Single or 1D array
print(arr1)


[1 2 3 4 5]


In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
print(arr1.shape)  # For 1D array it will show like this

(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #convert to a 2D array --> 1 row and 5 columns --> 2 square brackets indicate its 2D arary

array([[1, 2, 3, 4, 5]])

In [ ]:
arr3 = np.array([[1,2,3,4,5]])  #2D array
print(arr3)

[[1 2 3 4 5]]


In [ ]:
arr4 = np.array([[1,2,3,4,5],[4,5,6,7,8]])   # 2D array --> 2 rows and 5 columns
print(arr4)
arr4.shape

[[1 2 3 4 5]
 [4 5 6 7 8]]


(2, 5)

In [ ]:
np.arange(0,10,2).reshape(5,1)  # inbuilt function to create numpy arrays

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# identity matrix
#Means only diagonal elements will be on and all other elements will be zero
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print("Data type:",arr1.dtype)
print(arr1.size)
print(arr1.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
Data type: int64
6
8
